services:
  db:
    image: mysql:8.0
    container_name: django_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: "test1234"
    volumes:
      - ./mysql:/var/lib/mysql:rw
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
  web:
    build:
      context: .
    container_name: django_web
    command: >
      sh -c "python wait_for_db.py &&
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=test
      - DB_USER=root
      - DB_PASSWORD=test1234
      - DB_HOST=db
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "1234:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/static
    depends_on:
      - web

volumes:
  mysql: